version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: |
            yarn link
            yarn test
workflows:
  version: 2
  main:
    jobs:
      - build
